// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProfileService.Infrastructure.DbContext;

#nullable disable

namespace ProfileService.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProfileService.Core.Domain.Entities.Avatar", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileId")
                        .IsRequired()
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FileId");

                    b.HasIndex("ProfileId")
                        .IsUnique();

                    b.ToTable("Avatars");
                });

            modelBuilder.Entity("ProfileService.Core.Domain.Entities.Department", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("ProfileService.Core.Domain.Entities.File", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("ProfileService.Core.Domain.Entities.Profile", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Address")
                        .HasColumnType("jsonb")
                        .HasColumnName("Address");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DepartmentId")
                        .IsRequired()
                        .HasMaxLength(195)
                        .HasColumnType("character varying(195)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(195)
                        .HasColumnType("character varying(195)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(195)
                        .HasColumnType("character varying(195)");

                    b.Property<string>("FullName")
                        .HasMaxLength(195)
                        .HasColumnType("character varying(195)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SecondName")
                        .HasMaxLength(195)
                        .HasColumnType("character varying(195)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(195)
                        .HasColumnType("character varying(195)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(195)
                        .HasColumnType("character varying(195)");

                    b.Property<int>("UsersGrade")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("UserName", "Email")
                        .IsUnique();

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("ProfileService.Core.Domain.Entities.Avatar", b =>
                {
                    b.HasOne("ProfileService.Core.Domain.Entities.File", "File")
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProfileService.Core.Domain.Entities.Profile", "Profile")
                        .WithOne("Avatar")
                        .HasForeignKey("ProfileService.Core.Domain.Entities.Avatar", "ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("ProfileService.Core.Domain.Entities.Profile", b =>
                {
                    b.HasOne("ProfileService.Core.Domain.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("ProfileService.Core.Domain.Entities.Profile", b =>
                {
                    b.Navigation("Avatar");
                });
#pragma warning restore 612, 618
        }
    }
}
